### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by paperjack93** [marcialpaulg/Fixing-Cloudflare-Error-524#1]
the proposed fix does not work

**Comment by marcialpaulg** [comment]
I hope this new solution will fix your issue.

https://github.com/marcialpaulg/Fixing-Cloudflare-Error-524/blob/master/long-running-proccess-FIXED-2.php

**Comment by marcialpaulg** [comment]
I already pushed a working solution.

**Comment by marcialpaulg** [comment]
I already pushed a working solution.
